In [32]:
######## snakemake preamble start (automatically inserted, do not edit) ########
try:
    snakemake
except NameError:
    import sys; sys.path.extend(['/msc/home/mschae83/miniconda3/lib/python3.9/site-packages', '/msc/home/mschae83/cellwhisperer_private/src/figures/notebooks']); import pickle; snakemake = pickle.loads(b'\x80\x04\x95\xbb\x16\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8cX/msc/home/mschae83/cellwhisperer_private/results/finetuning_eval/geneformer/finetuned.pt\x94\x8cO/msc/home/mschae83/cellwhisperer_private/resources/immgen/read_count_table.h5ad\x94\x8c]/msc/home/mschae83/cellwhisperer_private/results/finetuning_eval/immgen/transfered_labels.csv\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\x05model\x94K\x00N\x86\x94\x8c\teval_data\x94K\x01N\x86\x94\x8c\x11transfered_labels\x94K\x02N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x18\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\x1e)}\x94\x8c\x05_name\x94h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\x10h\nh\x12h\x0bh\x14h\x0cub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8cb/msc/home/mschae83/cellwhisperer_private/results/finetuning_eval/geneformer/immgen/predictions.csv\x94\x8cb/msc/home/mschae83/cellwhisperer_private/results/finetuning_eval/geneformer/immgen/performance.csv\x94e}\x94(h\x0e}\x94(\x8c\x0bpredictions\x94K\x00N\x86\x94\x8c\x0bperformance\x94K\x01N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh0h,h2h-ub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94(K\x80\x8c\x08celltype\x94e}\x94(h\x0e}\x94(\x8c\nbatch_size\x94K\x00N\x86\x94\x8c\tlabel_col\x94K\x01N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bhDK\x80hFhAub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94(\x8c\ngeneformer\x94\x8c\x06immgen\x94e}\x94(h\x0e}\x94(\x8c\x05model\x94K\x00N\x86\x94\x8c\x07dataset\x94K\x01N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\x10hUh[hVub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x04/tmp\x94e}\x94(h\x0e}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bhnK\x01hpK\x01hrhkub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8c*logs/evaluate_scfm_geneformer_immgen.ipynb\x94a}\x94(h\x0e}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\x84h\x81ub\x8c\x06config\x94}\x94(\x8c\x12anndata_label_name\x94\x8c\x1bnatural_language_annotation\x94\x8c\x0enum_replicates\x94K\x05\x8c\x14llava_projector_type\x94\x8c\rmlp2x_8t_gelu\x94\x8c\x15precomputing_base_url\x94\x8c8https://medical-epigenomics.org/papers/schaefer2024/data\x94\x8c\x05paths\x94}\x94(\x8c\x10read_count_table\x94\x8c)resources/{dataset}/read_count_table.h5ad\x94\x8c\x0fraw_annotations\x94\x8c#resources/{dataset}/annotations.tsv\x94\x8c\x16structured_annotations\x94\x8c"results/{dataset}/annotations.json\x94\x8c\x15processed_annotations\x94\x8c,results/{dataset}/processed_annotations.json\x94\x8c\x1bprocessed_multi_annotations\x94\x8c2results/{dataset}/processed_multi_annotations.json\x94\x8c\x0bgeneset_gmt\x94\x8c\x1eresults/genesets/{library}.gmt\x94\x8c\x17model_processed_dataset\x94\x8c)results/{dataset}/{model}/full_output.npz\x94\x8c\x0cfull_dataset\x94\x8c results/{dataset}/full_data.h5ad\x94\x8c\x12enrichr_terms_json\x94\x8c"resources/enrichr_terms/terms.json\x94\x8c\x17ensembl_gene_symbol_map\x94\x8c%resources/ensembl_gene_symbol_map.csv\x94\x8c\x0fjointemb_models\x94\x8c\x17results/models/jointemb\x94\x8c\nwandb_logs\x94\x8c\x15results/wandb_logging\x94\x8c\x18datamodule_prepared_path\x94\x8c/results/{dataset}/lightning-processed/{hash}.pt\x94\x8c\x05cache\x94\x8c\rresults/cache\x94\x8c\x18cancer_gene_essentiality\x94}\x94(\x8c\x0fccle_expression\x94\x8c(CCLE_RNAseq_genes_counts_20180929.gct.gz\x94\x8c\x0fessential_genes\x94\x8cEresources/cancer_gene_essentiality/CRISPRInferredCommonEssentials.csv\x94\x8c\x12nonessential_genes\x94\x8cCresources/cancer_gene_essentiality/AchillesNonessentialControls.csv\x94u\x8c\x04gsva\x94}\x94(\x8c\x06result\x94\x8c\x1eresults/{dataset}/gsva.parquet\x94\x8c\x0bcorrelation\x94\x8c/results/{dataset}/{model}/gsva_correlations.csv\x94\x8c\x1ccw_transcriptome_term_scores\x94\x8c>results/{dataset}/{model}/cw_transcriptome_term_scores.parquet\x94\x8c\x05plots\x94\x8c0results/plots/gsva_correlation/{dataset}/{model}\x94u\x8c\x05llava\x94}\x94(\x8c\x04root\x94\x8c\x0eresults/llava/\x94\x8c\x15pretrain_text_dataset\x94\x8c!results/llava/pretrain_texts.json\x94\x8c\x15finetune_text_dataset\x94\x8c)results/llava/finetune_conversations.json\x94\x8c\x17evaluation_text_dataset\x94\x8c5results/llava/evaluation/{dataset}_conversations.json\x94\x8c\x17combined_processed_data\x94\x8c1results/llava/combined_processed_data/{model}.npz\x94\x8c\x14pretrained_model_dir\x94\x8c/results/llava/pretrained/{base_model}__{model}/\x94\x8c\x13finetuned_model_dir\x94\x8c.results/llava/finetuned/{base_model}__{model}/\x94\x8c\x12evaluation_results\x94\x8c4results/plots/llava/{dataset}/{base_model}__{model}/\x94u\x8c\x08geo_umap\x94\x8c\x1fresults/plots/geo_umap/{model}/\x94\x8c\tablations\x94}\x94(\x8c\x06models\x94\x8c\x19results/models/ablations/\x94\x8c\x05plots\x94\x8c\x18results/plots/ablations/\x94uu\x8c\nplot_style\x94\x8c\x19src/plot_style/main.style\x94\x8c\x08datasets\x94]\x94(\x8c\x06immgen\x94\x8c\rhuman_disease\x94\x8c\x0etabula_sapiens\x94\x8c!tabula_sapiens_100_cells_per_type\x94\x8c\narchs4_geo\x94\x8c\x11development4s_raw\x94\x8c\x16development_merged5000\x94\x8c\x05car_t\x94\x8c\rbowel_disease\x94\x8c\x0egut_cell_atlas\x94\x8c\x08pancreas\x94\x8c\x1chcaorganoids_normal__primary\x94\x8c\x1dhcaorganoids_normal__organoid\x94\x8c\x1chcaorganoids_cancer__primary\x94\x8c\x1dhcaorganoids_cancer__organoid\x94e\x8c\x1dzero_shot_validation_datasets\x94]\x94(\x8c\x06immgen\x94\x8c\rhuman_disease\x94\x8c\x0etabula_sapiens\x94\x8c\x08pancreas\x94\x8c%tabula_sapiens_well_studied_celltypes\x94e\x8c.metadata_cols_per_zero_shot_validation_dataset\x94}\x94(\x8c\x06immgen\x94]\x94\x8c\x08celltype\x94a\x8c\rhuman_disease\x94]\x94(\x8c\x0fDisease_subtype\x94\x8c\x06Tissue\x94e\x8c\x08pancreas\x94]\x94\x8c\x08celltype\x94a\x8c\x0etabula_sapiens\x94]\x94(\x8c\x08celltype\x94\x8c\x0corgan_tissue\x94e\x8c%tabula_sapiens_well_studied_celltypes\x94]\x94\x8c\x08celltype\x94a\x8c!tabula_sapiens_100_cells_per_type\x94]\x94(\x8c\x08celltype\x94\x8c\x0corgan_tissue\x94eu\x8c\x19retrieval_validation_sets\x94]\x94(\x8c\x13immgen_deduplicated\x94\x8cEhuman_disease_strictly_deduplicated_dmis-lab_biobert-v1.1_CLS_pooling\x94e\x8c\x13model_name_path_map\x94}\x94(\x8c\ngeneformer\x94\x8c\x1cresources/geneformer-12L-30M\x94\x8c\x06biogpt\x94\x8c\x10microsoft/biogpt\x94\x8c\x04bert\x94\x8c\x15dmis-lab/biobert-v1.1\x94\x8c\x05scgpt\x94\x8c\x15resources/scGPT_human\x94\x8c\rcellwhisperer\x94\x8c\x15cellwhisperer_clip_v1\x94\x8c\x0ellava_base_llm\x94\x8c\x18Mistral-7B-Instruct-v0.2\x94\x8c\x07mixtral\x94\x8c0resources/mixtral-8x7b-instruct-v0.1.Q5_K_M.gguf\x94u\x8c\x08genesets\x94]\x94(\x8c\x0cAzimuth_2023\x94\x8c\x1aGO_Biological_Process_2023\x94\x8c\x1aGO_Molecular_Function_2023\x94\x8c\rOMIM_Expanded\x94\x8c\x18PanglaoDB_Augmented_2021\x94\x8c\x0eTabula_Sapiens\x94e\x8c top20_lung_liver_blood_celltypes\x94]\x94(\x8c\nmacrophage\x94\x8c\x0berythrocyte\x94\x8c\x08monocyte\x94\x8c\x12type ii pneumocyte\x94\x8c\x12classical monocyte\x94\x8c\nneutrophil\x94\x8c\x1fcd4-positive, alpha-beta t cell\x94\x8c\x07nk cell\x94\x8c\x0cnaive b cell\x94\x8c\nbasal cell\x94\x8c\x1fcd8-positive, alpha-beta t cell\x94\x8c\nhepatocyte\x94\x8c;cd8-positive, alpha-beta cytokine secreting effector t cell\x94\x8c\tclub cell\x94\x8c\x16non-classical monocyte\x94\x8c\x1acapillary endothelial cell\x94\x8c&cd4-positive, alpha-beta memory t cell\x94\x8c\rmemory b cell\x94\x8c\x17respiratory goblet cell\x94\x8c\x08basophil\x94eu\x8c\x04rule\x94\x8c\teval_scfm\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8c>/msc/home/mschae83/cellwhisperer_private/src/figures/notebooks\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = False; import os; os.chdir(r'/msc/home/mschae83/cellwhisperer_private/src/figures');
######## snakemake preamble end #########

In [44]:
import pandas as pd
import numpy as np
import torch
import anndata

from zero_shot_validation_scripts.dataset_preparation import load_and_preprocess_dataset
from finetuning_eval.models.geneformer import GeneformerCelltypeModel
from cellwhisperer.jointemb.geneformer_model import GeneformerConfig, GeneformerTranscriptomeProcessor
import torchmetrics

In [ ]:
#### Load data
adata = load_and_preprocess_dataset(dataset_name=snakemake.wildcards.dataset, read_count_table_path = snakemake.input.eval_data)

#### Load transfered labels
transfered_labels = pd.read_csv(snakemake.input.transfered_labels)
transfered_labels

assert transfered_labels.evaluation_cell_type.nunique() == adata.obs[snakemake.params.label_col].nunique()

FileNotFoundError: [Errno 2] No such file or directory: '/msc/home/mschae83/cellwhisperer_private/results/finetuning_eval/immgen/transfered_labels.csv'

In [ ]:

label_col = snakemake.params.label_col
num_classes = len(adata.obs[label_col].unique())

if snakemake.wildcards.model == "geneformer":
    model = GeneformerCelltypeModel(GeneformerConfig(), num_classes=len(transfered_labels))
    transcriptome_processor = GeneformerTranscriptomeProcessor(snakemake.threads, ["natural_language_annotation"])  # second argument is irrelevant
    

model.load_state_dict(torch.load(snakemake.input.model))
model.eval()

GeneformerCelltypeModel(
  (output_layer): Linear(in_features=512, out_features=482, bias=True)
  (geneformer_model): GeneformerModel(
    (geneformer_model): BertForMaskedLM(
      (bert): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(25426, 512, padding_idx=0)
          (position_embeddings): Embedding(2048, 512)
          (token_type_embeddings): Embedding(2, 512)
          (LayerNorm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.02, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0-11): 12 x BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=512, out_features=512, bias=True)
                  (key): Linear(in_features=512, out_features=512, bias=True)
                  (value): Linear(in_features=512, out_features=512, bias=True)
                  (dropout): Dropout(p=0.02, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=512, out_features=512, bias=True)
                  (LayerNorm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.02, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=512, out_features=1024, bias=True)
                (intermediate_act_fn): ReLU()
              )
              (output): BertOutput(
                (dense): Linear(in_features=1024, out_features=512, bias=True)
                (LayerNorm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.02, inplace=False)
              )
            )
          )
        )
      )
      (cls): BertOnlyMLMHead(
        (predictions): BertLMPredictionHead(
          (transform): BertPredictionHeadTransform(
            (dense): Linear(in_features=512, out_features=512, bias=True)
            (transform_act_fn): ReLU()
            (LayerNorm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
          )
          (decoder): Linear(in_features=512, out_features=25426, bias=True)
        )
      )
    )
  )
)

In [46]:
inputs = transcriptome_processor(
    adata, return_tensors="pt", padding=True
)
inputs

{'expression_tokens': tensor([[17236, 17195, 24444,  ..., 13044,  3869, 17002],
         [24444,   396, 14436,  ...,  1985, 13533,  6222],
         [24444,   396, 16203,  ..., 11948, 11875,  5218],
         ...,
         [24444,   396, 16909,  ...,  5791,  5689,  5048],
         [ 8004, 24444,   269,  ..., 14918, 13727,  1792],
         [24444,  8004, 11780,  ...,   187, 13518, 11422]]),
 'expression_token_lengths': tensor([2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
         2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
         2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048,
         2048, 2048, 2048, 2048, 2048, 2048])}

In [ ]:
# Predict
batch_size = snakemake.params.batch_size
predictions = []
for i in range(0, len(adata), batch_size):
    batch = adata[i:i+batch_size]

    inputs = transcriptome_processor(
        batch, return_tensors="pt", padding=True
    )
    predictions.append(model(**inputs))

predictions = torch.cat(predictions)

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [86]:

# Save predictions
predictions_raw_df = pd.DataFrame(torch.softmax(predictions, 1).detach().numpy(), columns=transfered_labels.training_cell_type)
predictions_raw_df.index = adata.obs.index
predictions_raw_df.to_csv(snakemake.output.predictions_raw)

In [85]:
transfered_labels

                                    training_cell_type evaluation_cell_type
0                                 glutamatergic neuron                 none
1                                     GABAergic neuron                 none
2                                           glial cell                 none
3                                       dendritic cell      Dendritic cells
4                                          erythrocyte                 none
..                                                 ...                  ...
477                                        animal cell          animal cell
478  CD8-alpha-beta-positive, alpha-beta intraepith...              T cells
479                         neutrophil progenitor cell                 none
480                regular ventricular cardiac myocyte                 none
481                     regular atrial cardiac myocyte                 none

[482 rows x 2 columns]

In [91]:
# Aggregate the columns, according to the transfered labels

predictions_df = pd.DataFrame(index=adata.obs.index)
for evaluation_cell_type, training_cell_types in transfered_labels.groupby("evaluation_cell_type")["training_cell_type"]:
    predictions_df[evaluation_cell_type] = predictions_raw_df[training_cell_types].sum(axis=1)

predictions_df.to_csv(snakemake.output.predictions)

In [98]:
# Evaluate predictions using torchmetrics
labels = torch.tensor(adata.obs[label_col].cat.codes.values)
predictions = torch.tensor(predictions_df.values)

accuracy = torchmetrics.functional.accuracy(predictions, labels, average='macro', task="multiclass", num_classes=predictions_df.shape[1])
precision = torchmetrics.functional.precision(predictions, labels, average='macro', task="multiclass", num_classes=predictions_df.shape[1])
recall = torchmetrics.functional.recall(predictions, labels, average='macro', task="multiclass", num_classes=predictions_df.shape[1])
f1 = torchmetrics.functional.f1_score(predictions, labels, average='macro', task="multiclass", num_classes=predictions_df.shape[1])
auroc = torchmetrics.functional.auroc(torch.tensor(predictions_df.values), labels, task='multiclass', num_classes=predictions_df.shape[1])

performance = pd.DataFrame({"accuracy": [accuracy], "precision": [precision], "recall": [recall], "f1": [f1], "auroc": [auroc]})
performance.to_csv(snakemake.output.performance)

/msc/home/mschae83/miniconda3/envs/cellwhisperer/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
  warnings.warn(*args, **kwargs)  # noqa: B028

In [99]:
performance

     accuracy   precision      recall          f1           auroc
0  tensor(0.)  tensor(0.)  tensor(0.)  tensor(0.)  tensor(0.3413)