In [1]:
import pandas as pd
archs4_metadata = pd.read_csv(
    'archs4_sample_metadata.tsv.gz',
    sep = '\t',
    compression = 'gzip'
)
archs4_metadata

,geo_accession,characteristics_ch1,molecule_ch1,readsaligned,relation,series_id,singlecellprobability,source_name_ch1,title,srx_accession,biosample_accession
0,GSM1000981,"treatment: siNT,cell line: OCI-LY1",total RNA,102963402,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.007336,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,SRX185895,SAMN01163911
1,GSM1000982,"treatment: siNT,cell line: OCI-LY1",total RNA,85980162,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,-0.006492,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,SRX185896,SAMN01163912
2,GSM1000983,"treatment: siNT,cell line: OCI-LY1",total RNA,109810687,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,-0.006492,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,SRX185897,SAMN01163913
3,GSM1000984,"treatment: siBCL6,cell line: OCI-LY1",total RNA,105304785,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.007336,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,SRX185898,SAMN01163914
4,GSM1000985,"treatment: siBCL6,cell line: OCI-LY1",total RNA,97274296,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.030632,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,SRX185899,SAMN01163915
...,...,...,...,...,...,...,...,...,...,...,...
722420,GSM999587,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1225510,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.238154,Brain cortex,Parkinson's Disease PD 13,SRX185248,SAMN01163627
722421,GSM999588,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,2283349,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.009471,Brain cortex,Parkinson's Disease PD 14,SRX185249,SAMN01163628
722422,GSM999589,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,3253397,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.083552,Brain cortex,Parkinson's Disease PD 15,SRX185250,SAMN01163629
722423,GSM999590,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,511,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.333697,Brain cortex,Parkinson's Disease PD 16,SRX185251,SAMN01163630
722424,GSM999591,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1162666,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.019685,Brain cortex,Parkinson's Disease PD 17,SRX185252,SAMN01163631

In [2]:
sra_to_biosample = pd.read_csv(
    'sra_to_biosample.csv.gz',
    compression = 'gzip'
)
sra_to_biosample = sra_to_biosample.dropna().drop_duplicates()
sra_to_biosample.biosample = sra_to_biosample.biosample.astype(int)
sra_to_biosample

           sra  biosample
0       243394    1163911
1       243395    1163912
2       243396    1163913
3       243397    1163914
4       243398    1163915
...        ...        ...
722428  242745    1163627
722429  242746    1163628
722430  242747    1163629
722431  242748    1163630
722432  242749    1163631

[722243 rows x 2 columns]

In [3]:
sample_accessions = pd.read_csv(
    'sample_accessions.tsv.gz',
    sep = '\t',
    compression = 'gzip'
)
sample_accessions = sample_accessions.drop_duplicates()
sample_accessions

,biosample,uid,database,accession_type,experiment,sample,study,bioproject,geo
0,SAMN02383463,2398516,sra,biosample,SRX1671895,SRS1369054,SRP031885,PRJNA224140,GSM1249874
1,SAMN02383461,2398517,sra,biosample,SRX1671896,SRS1369053,SRP031885,PRJNA224140,GSM1249875
2,SAMN02383456,2398518,sra,biosample,SRX1671897,SRS1369052,SRP031885,PRJNA224140,GSM1249876
3,SAMN02383457,2398519,sra,biosample,SRX1671898,SRS1369051,SRP031885,PRJNA224140,GSM1249877
4,SAMN02383460,2398520,sra,biosample,SRX1671899,SRS1369050,SRP031885,PRJNA224140,GSM1249878
...,...,...,...,...,...,...,...,...,...
722420,SAMN29786852,23023289,sra,geo,SRX16311437,SRS13950350,SRP386774,PRJNA859437,GSM6341224
722421,SAMN29786851,23023290,sra,geo,SRX16311438,SRS13950351,SRP386774,PRJNA859437,GSM6341225
722422,SAMN29786850,23023291,sra,geo,SRX16311439,SRS13950352,SRP386774,PRJNA859437,GSM6341226
722423,SAMN29786849,23023292,sra,geo,SRX16311440,SRS13950353,SRP386774,PRJNA859437,GSM6341227
722424,SAMN29786848,23023293,sra,geo,SRX16311441,SRS13950354,SRP386774,PRJNA859437,GSM6341228

In [4]:
biosample_metadata = pd.read_csv(
    'biosample_metadata.csv.gz',
    compression = 'gzip'
)
biosample_metadata = biosample_metadata.drop_duplicates()
biosample_metadata

,title,attribute,organism,biosample
0,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163911
1,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163912
2,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163913
3,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163914
4,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,1163915
...,...,...,...,...
721942,Parkinson's Disease PD 13,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163627
721943,Parkinson's Disease PD 14,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163628
721944,Parkinson's Disease PD 15,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163629
721945,Parkinson's Disease PD 16,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163630
721946,Parkinson's Disease PD 17,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,1163631

In [5]:
metasra_metadata = pd.read_csv(
    'metasra_metadata.csv.gz',
    compression = 'gzip'
)
metasra_metadata = metasra_metadata.drop_duplicates()
metasra_metadata

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,assay
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369056,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369055,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369059,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,RNA-seq
...,...,...,...,...,...,...,...,...,...,...,...
170280,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361730,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
170281,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361740,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
170282,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361739,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
170283,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361732,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq
170284,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361737,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,RNA-seq

In [6]:
biosample_merged = sra_to_biosample.merge(
    biosample_metadata,
    on = 'biosample',
    how = 'inner'
)
biosample_merged

,sra,biosample,title,attribute,organism
0,243394,1163911,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606
1,243395,1163912,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606
2,243396,1163913,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606
3,243397,1163914,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606
4,243398,1163915,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606
...,...,...,...,...,...
722238,242745,1163627,Parkinson's Disease PD 13,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606
722239,242746,1163628,Parkinson's Disease PD 14,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606
722240,242747,1163629,Parkinson's Disease PD 15,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606
722241,242748,1163630,Parkinson's Disease PD 16,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606
722242,242749,1163631,Parkinson's Disease PD 17,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606

In [7]:
accession_merged = biosample_merged \
    .rename(
        columns = {
            'sra': 'sra_uid',
            'biosample': 'biosample_uid',
            'title': 'biosample_title',
            'attribute': 'raw_biosample_metadata'
        }
    ).merge(
        sample_accessions.rename(
            columns = {
                'uid': 'sra_uid'
            }
        ),
        on = 'sra_uid',
        how = 'inner'
    )
accession_merged

,sra_uid,biosample_uid,biosample_title,raw_biosample_metadata,organism,biosample,database,accession_type,experiment,sample,study,bioproject,geo
0,243394,1163911,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,SAMN01163911,sra,experiment,SRX185895,SRS362050,SRP007525,PRJNA138597,GSM1000981
1,243395,1163912,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,SAMN01163912,sra,experiment,SRX185896,SRS362051,SRP007525,PRJNA138597,GSM1000982
2,243396,1163913,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,SAMN01163913,sra,experiment,SRX185897,SRS362052,SRP007525,PRJNA138597,GSM1000983
3,243397,1163914,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,SAMN01163914,sra,experiment,SRX185898,SRS362053,SRP007525,PRJNA138597,GSM1000984
4,243398,1163915,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2,source_name: Human DLBCL cel line; treatment: ...,Homo sapiens;9606,SAMN01163915,sra,experiment,SRX185899,SRS362054,SRP007525,PRJNA138597,GSM1000985
...,...,...,...,...,...,...,...,...,...,...,...,...,...
722238,242745,1163627,Parkinson's Disease PD 13,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163627,sra,experiment,SRX185248,SRS361742,SRP015668,PRJNA174763,GSM999587
722239,242746,1163628,Parkinson's Disease PD 14,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163628,sra,experiment,SRX185249,SRS361743,SRP015668,PRJNA174763,GSM999588
722240,242747,1163629,Parkinson's Disease PD 15,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163629,sra,experiment,SRX185250,SRS361744,SRP015668,PRJNA174763,GSM999589
722241,242748,1163630,Parkinson's Disease PD 16,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163630,sra,experiment,SRX185251,SRS361745,SRP015668,PRJNA174763,GSM999590
722242,242749,1163631,Parkinson's Disease PD 17,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163631,sra,experiment,SRX185252,SRS361746,SRP015668,PRJNA174763,GSM999591

In [8]:
metasra_merged = metasra_metadata.merge(
    accession_merged.rename(
        columns = {
            'sample': 'sample_id'
        }
    ),
    on = 'sample_id',
    how = 'inner'
)
metasra_merged

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,...,biosample_title,raw_biosample_metadata,organism,biosample,database,accession_type,experiment,study,bioproject,geo
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,Gro-seq-siBrd4-1-re2-HEK293T,source_name: HEK293T cell; cell_line: Human Em...,Homo sapiens;9606,SAMN02383457,sra,biosample,SRX1671898,SRP031885,PRJNA224140,GSM1249877
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,Gro-seq-siBrd4-2-re2-HEK293T,source_name: HEK293T cell; cell_line: Human Em...,Homo sapiens;9606,SAMN02383460,sra,biosample,SRX1671899,SRP031885,PRJNA224140,GSM1249878
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369054,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,Gro-seq-siCTL-re2-HEK293T,source_name: HEK293T cell; cell_line: Human Em...,Homo sapiens;9606,SAMN02383463,sra,biosample,SRX1671895,SRP031885,PRJNA224140,GSM1249874
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369053,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,Gro-seq-siJMJD6-1-re2-HEK293T,source_name: HEK293T cell; cell_line: Human Em...,Homo sapiens;9606,SAMN02383461,sra,biosample,SRX1671896,SRP031885,PRJNA224140,GSM1249875
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369052,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,Gro-seq-siJMJD6-2-re2-HEK293T,source_name: HEK293T cell; cell_line: Human Em...,Homo sapiens;9606,SAMN02383456,sra,biosample,SRX1671897,SRP031885,PRJNA224140,GSM1249876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162569,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361730,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,Parkinson's Disease PD 1,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163615,sra,experiment,SRX185236,SRP015668,PRJNA174763,GSM999575
162570,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361740,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,Parkinson's Disease PD 11,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163625,sra,experiment,SRX185246,SRP015668,PRJNA174763,GSM999585
162571,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361739,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,Parkinson's Disease PD 10,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163624,sra,experiment,SRX185245,SRP015668,PRJNA174763,GSM999584
162572,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361732,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,Parkinson's Disease PD 3,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163617,sra,experiment,SRX185238,SRP015668,PRJNA174763,GSM999577
162573,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361737,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,Parkinson's Disease PD 8,source_name: Brain cortex; tissue: Human brain...,Homo sapiens;9606,SAMN01163622,sra,experiment,SRX185243,SRP015668,PRJNA174763,GSM999582

In [9]:
archs4_merged = metasra_merged.merge(
    archs4_metadata.drop(
        columns = [
            'srx_accession', 
            'biosample_accession'
        ]
    ).rename(
        columns = {
            'geo_accession': 'geo',
            'title': 'geo_title',
            'source_name_ch1': 'geo_source_name',
            'characteristics_ch1': 'geo_metadata'
        }
    ),
    on = 'geo',
    how = 'inner'
)
archs4_merged

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,...,bioproject,geo,geo_metadata,molecule_ch1,readsaligned,relation,series_id,singlecellprobability,geo_source_name,geo_title
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249877,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9955958,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.003674,HEK293T cell,Gro-seq-siBrd4-1-re2-HEK293T
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249878,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,11310969,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.002638,HEK293T cell,Gro-seq-siBrd4-2-re2-HEK293T
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369054,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249874,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9563021,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,0.005895,HEK293T cell,Gro-seq-siCTL-re2-HEK293T
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369053,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249875,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9164074,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,0.000674,HEK293T cell,Gro-seq-siJMJD6-1-re2-HEK293T
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369052,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249876,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9114591,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.002878,HEK293T cell,Gro-seq-siJMJD6-2-re2-HEK293T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162569,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361730,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,PRJNA174763,GSM999575,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1436357,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.121897,Brain cortex,Parkinson's Disease PD 1
162570,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361740,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,PRJNA174763,GSM999585,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1143089,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.113353,Brain cortex,Parkinson's Disease PD 11
162571,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361739,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,PRJNA174763,GSM999584,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1991755,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.004230,Brain cortex,Parkinson's Disease PD 10
162572,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361732,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,PRJNA174763,GSM999577,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1108707,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.150055,Brain cortex,Parkinson's Disease PD 3
162573,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361737,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,PRJNA174763,GSM999582,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1630827,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.122946,Brain cortex,Parkinson's Disease PD 8

In [23]:
spurious_duplication = archs4_merged.sra_uid.duplicated(keep = False)
archs4_merged_nd = archs4_merged.loc[~spurious_duplication, :]
archs4_merged_d = archs4_merged.loc[spurious_duplication, :]

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,...,bioproject,geo,geo_metadata,molecule_ch1,readsaligned,relation,series_id,singlecellprobability,geo_source_name,geo_title
146025,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125738,Activated Macrophage,primary cells,0.632759,"CL:0000235, EFO:0000727","macrophage, treatment",cell type: Activated Macrophage; treatment: PBS,human,...,PRJNA555592,GSM3955790,"cell type: Activated Macrophage,treatment: TGFb1",total RNA,28869433,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002442,Activated Macrophage,Activated Macrophage treated with TGFb1 1
146026,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125738,Activated Macrophage,primary cells,0.632759,"CL:0000235, EFO:0000727","macrophage, treatment",cell type: Activated Macrophage; treatment: PBS,human,...,PRJNA555592,GSM3955790,"cell type: Activated Macrophage,treatment: TGFb1",total RNA,28869433,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002442,Activated Macrophage,Activated Macrophage treated with TGFb1 1
146027,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125739,Activated Macrophage,primary cells,0.632759,"CL:0000235, EFO:0000727","macrophage, treatment",cell type: Activated Macrophage; treatment: TGFb1,human,...,PRJNA555592,GSM3955789,"cell type: Activated Macrophage,treatment: PBS",total RNA,34137179,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002521,Activated Macrophage,Activated Macrophage treated with PBS 2
146028,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125739,Activated Macrophage,primary cells,0.632759,"CL:0000235, EFO:0000727","macrophage, treatment",cell type: Activated Macrophage; treatment: TGFb1,human,...,PRJNA555592,GSM3955789,"cell type: Activated Macrophage,treatment: PBS",total RNA,34137179,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002521,Activated Macrophage,Activated Macrophage treated with PBS 2
146031,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125734,CD4+ effector memory T cells,primary cells,0.589320,"CL:0000897, EFO:0000727","CD4-positive, alpha-beta memory T cell, treatment",cell type: CD4+ effector memory T cells; treat...,human,...,PRJNA555592,GSM3955786,"cell type: CD4+ effector memory T cells,treatm...",total RNA,27147751,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.003780,CD4+ effector memory T cells,CD4+ effector memory T cells treated with TGFb1 1
146032,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125734,CD4+ effector memory T cells,primary cells,0.589320,"CL:0000897, EFO:0000727","CD4-positive, alpha-beta memory T cell, treatment",cell type: CD4+ effector memory T cells; treat...,human,...,PRJNA555592,GSM3955786,"cell type: CD4+ effector memory T cells,treatm...",total RNA,27147751,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.003780,CD4+ effector memory T cells,CD4+ effector memory T cells treated with TGFb1 1
146033,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125736,CD4+ effector memory T cells,primary cells,0.589320,"CL:0000897, EFO:0000727","CD4-positive, alpha-beta memory T cell, treatment",cell type: CD4+ effector memory T cells; treat...,human,...,PRJNA555592,GSM3955785,"cell type: CD4+ effector memory T cells,treatm...",total RNA,28677070,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002268,CD4+ effector memory T cells,CD4+ effector memory T cells treated with PBS 2
146034,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125736,CD4+ effector memory T cells,primary cells,0.589320,"CL:0000897, EFO:0000727","CD4-positive, alpha-beta memory T cell, treatment",cell type: CD4+ effector memory T cells; treat...,human,...,PRJNA555592,GSM3955785,"cell type: CD4+ effector memory T cells,treatm...",total RNA,28677070,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002268,CD4+ effector memory T cells,CD4+ effector memory T cells treated with PBS 2
146037,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125725,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955778,"cell type: endothelial cells (HUVEC),treatment...",total RNA,31352052,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.004471,endothelial cells (HUVEC),endothelial cells treated with TGFb1 1
146038,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125725,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955778,"cell type: endothelial cells (HUVEC),treatment...",total RNA,31352052,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.004471,endothelial cells (HUVEC),endothelial cells treated with TGFb1 1
146039,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125727,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955777,"cell type: endothelial cells (HUVEC),treatment...",total RNA,32992165,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.011775,endothelial cells (HUVEC),endothelial cells treated with PBS 2
146040,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125727,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955777,"cell type: endothelial cells (HUVEC),treatment...",total RNA,32992165,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.011775,endothelial cells (HUVEC),endothelial cells treated with PBS 2
146043,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125731,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955782,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,25430602,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.003805,smooth muscle cells (HASMC),smooth muscle cells treated with TGFb1 1
146044,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125731,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955782,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,25430602,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.003805,smooth muscle cells (HASMC),smooth muscle cells treated with TGFb1 1
146045,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125730,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955781,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,27804320,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.001844,smooth muscle cells (HASMC),smooth muscle cells treated with PBS 2
146046,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125730,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955781,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,27804320,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.001844,smooth muscle cells (HASMC),smooth muscle cells treated with PBS 2

In [34]:
def normalize_string(string):
    normalized_string = []
    for char in string:
        if ord(char) < 128 and char != ' ':
            normalized_string.append(char)
    
    return ''.join(normalized_string)


def all_equal(x):
    ref = normalize_string(x.iloc[0])
    return all(normalize_string(item) == ref for _, item in x.items())


all_equal_idx = archs4_merged_d[['geo_title', 'biosample_title']].apply(
    all_equal,
    axis = 1
)
archs4_merged_d.loc[
    all_equal_idx, 
    ['geo_source_name', 'geo_title', 'biosample_title', 'sample_name', 'biosample', 'experiment']
]

,geo_source_name,geo_title,biosample_title,sample_name,biosample,experiment
146026,Activated Macrophage,Activated Macrophage treated with TGFb1 1,Activated Macrophage treated with TGFb1 1,Activated Macrophage,SAMN12323886,SRX6476485
146027,Activated Macrophage,Activated Macrophage treated with PBS 2,Activated Macrophage treated with PBS 2,Activated Macrophage,SAMN12323885,SRX6476484
146032,CD4+ effector memory T cells,CD4+ effector memory T cells treated with TGFb1 1,CD4+ effector memory T cells treated with TGFb1 1,CD4+ effector memory T cells,SAMN12323853,SRX6476481
146033,CD4+ effector memory T cells,CD4+ effector memory T cells treated with PBS 2,CD4+ effector memory T cells treated with PBS 2,CD4+ effector memory T cells,SAMN12323852,SRX6476480
146038,endothelial cells (HUVEC),endothelial cells treated with TGFb1 1,endothelial cells treated with TGFb1 1,endothelial cells (HUVEC),SAMN12323862,SRX6476473
146039,endothelial cells (HUVEC),endothelial cells treated with PBS 2,endothelial cells treated with PBS 2,endothelial cells (HUVEC),SAMN12323860,SRX6476472
146044,smooth muscle cells (HASMC),smooth muscle cells treated with TGFb1 1,smooth muscle cells treated with TGFb1 1,smooth muscle cells (HASMC),SAMN12323857,SRX6476477
146045,smooth muscle cells (HASMC),smooth muscle cells treated with PBS 2,smooth muscle cells treated with PBS 2,smooth muscle cells (HASMC),SAMN12323856,SRX6476476

In [30]:
archs4_merged_deduplicated = pd.concat(
    [
        archs4_merged_nd,
        archs4_merged_d.loc[all_equal_idx, :]
    ]
)
archs4_merged_deduplicated.reset_index(drop = True, inplace = True)
archs4_merged_deduplicated

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,...,bioproject,geo,geo_metadata,molecule_ch1,readsaligned,relation,series_id,singlecellprobability,geo_source_name,geo_title
0,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369051,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249877,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9955958,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.003674,HEK293T cell,Gro-seq-siBrd4-1-re2-HEK293T
1,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369050,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249878,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,11310969,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.002638,HEK293T cell,Gro-seq-siBrd4-2-re2-HEK293T
2,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369054,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249874,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9563021,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,0.005895,HEK293T cell,Gro-seq-siCTL-re2-HEK293T
3,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369053,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249875,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9164074,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,0.000674,HEK293T cell,Gro-seq-siJMJD6-1-re2-HEK293T
4,SRP031885,Brd4 and JMJD6-associated Anti-pause Enhancers...,SRS1369052,HEK293T cell,cell line,1.000000,"CL:0000010, CVCL:0045, EFO:0001182, EFO:000072...","cultured cell, HEK293, transfection, kidney",cell line: Human Embryonic Kidney 293 cells; s...,human,...,PRJNA224140,GSM1249876,"cell line: Human Embryonic Kidney 293 cells,si...",total RNA,9114591,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE51633,-0.002878,HEK293T cell,Gro-seq-siJMJD6-2-re2-HEK293T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162561,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125736,CD4+ effector memory T cells,primary cells,0.589320,"CL:0000897, EFO:0000727","CD4-positive, alpha-beta memory T cell, treatment",cell type: CD4+ effector memory T cells; treat...,human,...,PRJNA555592,GSM3955785,"cell type: CD4+ effector memory T cells,treatm...",total RNA,28677070,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.002268,CD4+ effector memory T cells,CD4+ effector memory T cells treated with PBS 2
162562,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125725,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955778,"cell type: endothelial cells (HUVEC),treatment...",total RNA,31352052,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.004471,endothelial cells (HUVEC),endothelial cells treated with TGFb1 1
162563,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125727,endothelial cells (HUVEC),cell line,0.545362,"CL:0000115, EFO:0000727","endothelial cell, treatment",cell type: endothelial cells (HUVEC); treatmen...,human,...,PRJNA555592,GSM3955777,"cell type: endothelial cells (HUVEC),treatment...",total RNA,32992165,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.011775,endothelial cells (HUVEC),endothelial cells treated with PBS 2
162564,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125731,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955782,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,25430602,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.003805,smooth muscle cells (HASMC),smooth muscle cells treated with TGFb1 1
162565,SRP215472,Endothelial TGFb signaling drives vascular inf...,SRS5125730,smooth muscle cells (HASMC),cell line,0.545362,"CL:0000192, EFO:0000727","smooth muscle cell, treatment",cell type: smooth muscle cells (HASMC); treatm...,human,...,PRJNA555592,GSM3955781,"cell type: smooth muscle cells (HASMC),treatme...",total RNA,27804320,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,"GSE134555,GSE134558",0.001844,smooth muscle cells (HASMC),smooth muscle cells treated with PBS 2

In [31]:
from metadatamapping import archs4

archs4_data = archs4.samples(
    'human_gene_v2.2.h5',
    archs4_merged_deduplicated.geo,
    n_processes = 4
)
archs4_data

/users/daniel.malzl/.conda/envs/scllm/lib/python3.12/site-packages/anndata/_core/anndata.py:1899: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 162566 × 67186

In [32]:
archs4_data.obs = archs4_data.obs.merge(
    archs4_merged_deduplicated.set_index('geo'),
    left_index = True,
    right_index = True,
    how = 'left'
)

In [33]:
archs4_data.obs

,study_id,study_title,sample_id,sample_name,sample_type,sample_type_confidence,mapped_ontology_ids,mapped_ontology_terms,raw_SRA_metadata,sample_species,...,study,bioproject,geo_metadata,molecule_ch1,readsaligned,relation,series_id,singlecellprobability,geo_source_name,geo_title
GSM1000981,SRP007525,A Hybrid Mechanism of Action for BCL6 in B Cel...,SRS362050,Human DLBCL cel line,cell line,1.000000,"CL:0000010, CVCL:1879, EFO:0000403, EFO:000072...","cultured cell, OCI-Ly1, diffuse large B-cell l...",cell line: OCI-LY1; treatment: siNT,human,...,SRP007525,PRJNA138597,"treatment: siNT,cell line: OCI-LY1",total RNA,102963402,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.007336,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R1
GSM1000982,SRP007525,A Hybrid Mechanism of Action for BCL6 in B Cel...,SRS362051,Human DLBCL cel line,cell line,1.000000,"CL:0000010, CVCL:1879, EFO:0000403, EFO:000072...","cultured cell, OCI-Ly1, diffuse large B-cell l...",cell line: OCI-LY1; treatment: siNT,human,...,SRP007525,PRJNA138597,"treatment: siNT,cell line: OCI-LY1",total RNA,85980162,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,-0.006492,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R2
GSM1000983,SRP007525,A Hybrid Mechanism of Action for BCL6 in B Cel...,SRS362052,Human DLBCL cel line,cell line,1.000000,"CL:0000010, CVCL:1879, EFO:0000403, EFO:000072...","cultured cell, OCI-Ly1, diffuse large B-cell l...",cell line: OCI-LY1; treatment: siNT,human,...,SRP007525,PRJNA138597,"treatment: siNT,cell line: OCI-LY1",total RNA,109810687,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,-0.006492,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siNT_R3
GSM1000984,SRP007525,A Hybrid Mechanism of Action for BCL6 in B Cel...,SRS362053,Human DLBCL cel line,cell line,1.000000,"CL:0000010, CVCL:1879, EFO:0000403, EFO:000072...","cultured cell, OCI-Ly1, diffuse large B-cell l...",cell line: OCI-LY1; treatment: siBCL6,human,...,SRP007525,PRJNA138597,"treatment: siBCL6,cell line: OCI-LY1",total RNA,105304785,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.007336,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R1
GSM1000985,SRP007525,A Hybrid Mechanism of Action for BCL6 in B Cel...,SRS362054,Human DLBCL cel line,cell line,1.000000,"CL:0000010, CVCL:1879, EFO:0000403, EFO:000072...","cultured cell, OCI-Ly1, diffuse large B-cell l...",cell line: OCI-LY1; treatment: siBCL6,human,...,SRP007525,PRJNA138597,"treatment: siBCL6,cell line: OCI-LY1",total RNA,97274296,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE29282,0.030632,Human DLBCL cel line,OCI-LY1_48hrs_mRNAseq_3x_siBCL6_R2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GSM999587,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361742,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,SRP015668,PRJNA174763,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1225510,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.238154,Brain cortex,Parkinson's Disease PD 13
GSM999588,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361743,Brain cortex,tissue,0.955796,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, fem...",disease state: Parkinson's Disease PD; gender:...,human,...,SRP015668,PRJNA174763,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,2283349,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.009471,Brain cortex,Parkinson's Disease PD 14
GSM999589,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361744,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,SRP015668,PRJNA174763,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,3253397,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.083552,Brain cortex,Parkinson's Disease PD 15
GSM999590,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361745,Brain cortex,tissue,0.945379,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, mal...",disease state: Parkinson's Disease PD; gender:...,human,...,SRP015668,PRJNA174763,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,511,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.333697,Brain cortex,Parkinson's Disease PD 16
GSM999591,SRP015668,aSyn polyA-RNAseq in PD and unaffected cortica...,SRS361746,Brain cortex,tissue,0.955796,"DOID:14330, EFO:0002508, EFO:0003534, UBERON:0...","Parkinson's disease, dorsal telencephalon, fem...",disease state: Parkinson's Disease PD; gender:...,human,...,SRP015668,PRJNA174763,"tissue: Human brain cortex (BA9),disease state...",polyA RNA,1162666,SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX...,GSE40710,0.019685,Brain cortex,Parkinson's Disease PD 17

In [38]:
archs4_data.write('archs4_annotated.h5ad')